name: nosqlclient # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '4.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: MongoDB Management Tool 
description: |
  Long description of nosqlclient

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  nosqlclient:
    command: meteor npm install && meteor
    daemon: simple

parts:
  meteor:
    source: https://static-meteor.netdna-ssl.com/packages-bootstrap/1.10.2/meteor-bootstrap-os.linux.x86_64.tar.gz
    plugin: dump

  nosqlclient:
    source: ../
    plugin: dump

